/**
 * Suggestion / SuggestionQueue — proactive memory v3.0
 *
 * Suggestions are ephemeral, in-memory hints generated by IntentPredictor.
 * They flow: create → queue → inject → (acted_on / ignored / expired).
 */
import { randomUUID } from 'node:crypto';

export type SuggestionType = 'suggestion' | 'alert' | 'reminder';
export type SuggestionStatus =
  | 'pending'
  | 'injected'
  | 'acted_on'
  | 'ignored'
  | 'expired';

export interface Suggestion {
  readonly id: string;
  readonly type: SuggestionType;
  readonly priority: number; // 0-1
  readonly summary: string;
  readonly detail: string;
  readonly confidence: number; // 0-1
  readonly sourcePatternIds: readonly string[];
  readonly createdAt: Date;
  readonly expiresAt: Date;
  status: SuggestionStatus;
  injectedAt: Date | null;
}

export interface SuggestionCreateInput {
  type: SuggestionType;
  priority: number;
  summary: string;
  detail: string;
  confidence: number;
  sourcePatternIds: readonly string[];
  /** TTL in ms from now (default 30 min) */
  ttlMs?: number;
}

const DEFAULT_SUGGESTION_TTL_MS = 30 * 60 * 1000; // 30 minutes
const MAX_QUEUE_SIZE = 10;

export function createSuggestion(input: SuggestionCreateInput): Suggestion {
  const now = new Date();
  const ttl = input.ttlMs ?? DEFAULT_SUGGESTION_TTL_MS;
  return {
    id: randomUUID(),
    type: input.type,
    priority: input.priority,
    summary: input.summary,
    detail: input.detail,
    confidence: input.confidence,
    sourcePatternIds: input.sourcePatternIds,
    createdAt: now,
    expiresAt: new Date(now.getTime() + ttl),
    status: 'pending',
    injectedAt: null,
  };
}

export class SuggestionQueue {
  private queue: Suggestion[] = [];
  private readonly maxSize: number;
  private readonly nowFn: () => Date;

  constructor(options: { maxSize?: number; now?: () => Date } = {}) {
    this.maxSize = options.maxSize ?? MAX_QUEUE_SIZE;
    this.nowFn = options.now ?? (() => new Date());
  }

  enqueue(input: SuggestionCreateInput): Suggestion | null {
    this.expireStale();
    if (this.queue.length >= this.maxSize) {
      return null;
    }
    const suggestion = createSuggestion(input);
    this.queue.push(suggestion);
    return suggestion;
  }

  dequeue(count: number = 1): Suggestion[] {
    this.expireStale();
    const ready = this.queue
      .filter(s => s.status === 'pending')
      .sort((a, b) => b.priority - a.priority)
      .slice(0, count);

    for (const s of ready) {
      s.status = 'injected';
      s.injectedAt = this.nowFn();
    }
    return ready;
  }

  getActive(): Suggestion[] {
    this.expireStale();
    return this.queue.filter(s => s.status === 'pending');
  }

  markActedOn(id: string): void {
    const s = this.queue.find(item => item.id === id);
    if (s) s.status = 'acted_on';
  }

  markIgnored(id: string): void {
    const s = this.queue.find(item => item.id === id);
    if (s) s.status = 'ignored';
  }

  expireStale(): number {
    const now = this.nowFn();
    let expiredCount = 0;
    for (const s of this.queue) {
      if (
        (s.status === 'pending' || s.status === 'injected') &&
        now >= s.expiresAt
      ) {
        s.status = 'expired';
        expiredCount++;
      }
    }
    return expiredCount;
  }

  get all(): readonly Suggestion[] {
    return [...this.queue];
  }

  get pendingCount(): number {
    return this.queue.filter(s => s.status === 'pending').length;
  }

  size(): number {
    return this.queue.length;
  }

  clear(): void {
    this.queue = [];
  }
}
